import { Inter } from "next/font/google";
import "./globals.css";

// Initialize the Inter font with specific subsets
const inter = Inter({ subsets: ["latin"] });

// Metadata for the application
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component for the Next.js application.
 * 
 * @param {Object} props - The component props.
 * @param {React.ReactNode} props.children - Child components to be rendered inside the layout.
 * @returns {JSX.Element} The JSX rendering of the layout.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
